apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: redis-monitor
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: redis
  endpoints:
  - port: metrics