apiVersion: v1
kind: ConfigMap
metadata:
  name: web-code-config
data:
  app.py: |
    import os
    import time
    from flask import Flask
    import redis

    app = Flask(__name__)
    
    redis_host = os.getenv('REDIS_HOST', 'localhost')
    redis_password = os.getenv('REDIS_PASS', '')
    cache = redis.Redis(host=redis_host, port=6379, password=redis_password)

    def get_hit_count():
        retries = 5
        while True:
            try:
                return cache.incr('hits')
            except redis.exceptions.ConnectionError as exc:
                if retries == 0:
                    raise exc
                retries -= 1
                time.sleep(0.5)

    @app.route('/')
    def hello():
        count = get_hit_count()
        return 'Hello Kubernetes! I have been seen {} times.\n'.format(count)

    if __name__ == "__main__":
        app.run(host="0.0.0.0", port=5000)
